******************
Use-Case 1 Diagram
******************

@startuml

actor Usr as "User"


rectangle Database

rectangle "Use case 1" {
    usecase UC1 as "User chooses city
    to get population report from"


    usecase UCa as "Print data"

    Usr - UC1

    UC1 ..> UCa : include

    UCa - Database
}

@enduml

******************
Use-Case 2 Diagram
******************

@startuml

actor Usr as "User"


rectangle Database

rectangle "Use case 1" {
    usecase UC1 as "User chooses district
    to get population report from"


    usecase UCa as "Print data"

    Usr - UC1

    UC1 ..> UCa : include

    UCa - Database
}

@enduml


******************
Use-Case 3 Diagram
******************

@startuml

actor Usr as "User"


rectangle Database

rectangle "Use case 1" {
    usecase UC1 as "User chooses country
    to get population report from"


    usecase UCa as "Print data"

    Usr - UC1

    UC1 ..> UCa : include

    UCa - Database
}

@enduml

******************
Use-Case 4 Diagram
******************

@startuml

actor Usr as "User"


rectangle Database

rectangle "Use case 1" {
    usecase UC1 as "User chooses a continent
    to get population report from"


    usecase UCa as "Print data"

    Usr - UC1

    UC1 ..> UCa : include

    UCa - Database
}

@enduml


******************
Use-Case 5 Diagram
******************

@startuml

actor Usr as "User"


rectangle Database

rectangle "Use case 1" {
    usecase UC1 as "User chooses region
    to get population report from"


    usecase UCa as "Print data"

    Usr - UC1

    UC1 ..> UCa : include

    UCa - Database
}

@enduml

******************
Use-Case 6 Diagram
******************

@startuml

actor Usr as "User"


rectangle Database

rectangle "Use case 1" {
    usecase UC1 as "User chooses city
    to get population report from"


    usecase UCa as "Print data"

    Usr - UC1

    UC1 ..> UCa : include

    UCa - Database
}

@enduml
























































******************
Use-Case 2 Diagram
******************

@startuml

actor Usr as "User"
actor Usr1 as "User"

rectangle Database

rectangle "Use case 2" {
    usecase UC1 as "Program prompts
    user to make language
    selection"

    usecase UC1a as "User makes selection"

    usecase UCa as "Print data"

        Usr - UC1
        Usr1 - UC1a
        UC1 ..> UC1a : include
        UC1a ..> UCa
        UCa - Database
    }

    @enduml

}


























































******************
Use-Case 3 Diagram
******************

@startuml

actor Usr as "User"
actor Usr1 as "User"
actor Usr2 as "User"

rectangle Database

rectangle "Use Case 3" {
    usecase UC1 as "Program prompts user to
    enter geographical location"

    usecase UC1a as "User makes selection"

    usecase UC1b as "Program prompts user to
    select how they would like data
    formatted (largest/smallest/ect)"

    usecase UC1c as "User makes selection"

    usecase UC1d as "Print Data"

        Usr - UC1
        Usr1 - UC1a
        Usr2 - UC1c
        UC1d - Database

        UC1 ..> UC1a
        UC1a ..> UC1b
        UC1b ..> UC1c
        UC1c ..> UC1d
    }

    @enduml
}