******************
Use-Case Diagram
******************

@startuml


actor Prg as "Programmer"
rectangle database
   left to right direction
rectangle "project" {

    usecase UC1 as " get population data from those living in cities in each country / region / continent"
    usecase UC2 as " get population data from those outwith cities in each country / region / continent"
    usecase UC3 as " get all capital cities in the  region / continent / world organised by largest population to smallest"
    usecase UC4 as "get all cities in the district/ country  / region / continent / world organised by largest population to smallest"
    usecase UC5 as "get top N populated capital cities in region / continent / world"
    usecase UC6 as "get top N populated cities in district / country  / region / continent / world"
    usecase UC7 as "get top N populated countries in the region / continent / world"
    usecase UC8 as "get all populated countries in the region / continent / world organised by largest population to smallest"
}
    usecase UCa as "Print data"

    Prg --> UC1
    Prg --> UC2
    Prg --> UC3
    Prg --> UC4
    Prg --> UC8
    Prg --> UC5
    Prg --> UC6
    Prg --> UC7
          UC1 <-down- database :include
          UC2 <-down- database :include
          UC3 <-down- database :include
          UC4 <-down- database :include
          UC5 <-down- database :include
          UC6 <-down- database :include
          UC7 <-down- database :include
          UC1 -->  UCa
          UC2 -->  UCa
          UC3 -->  UCa
          UC4 -->  UCa
          UC5 -->  UCa
          UC6 -->  UCa
          UC7 -->  UCa
          UC8 -->  UCa



@enduml

